name: release-please

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write
  checks: write
  statuses: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
